import Anthropic from "@anthropic-ai/sdk";

export const anthropic = new Anthropic();

// Sonnet 5: near-Opus reasoning (needed to avoid generic findings), high-res
// vision, and intro pricing ($2/$10 per MTok through 2026-08-31). Thinking is
// disabled and JSON is forced via structured outputs for speed + cost.
export const MODEL = "claude-sonnet-5";

// Connection throughput in bytes/second, from the spec. Load time is COMPUTED
// from real screenshot bytes and passed into the prompt as a fact — never
// generated by the model.
const THROUGHPUT: Record<string, number> = { "2G": 30000, "3G": 120000, "4G": 400000 };

export function loadSeconds(bytes: number, connection: string): number {
  const bps = THROUGHPUT[connection] ?? THROUGHPUT["3G"];
  return Math.round((bytes / bps) * 10) / 10;
}

export type ImageMediaType = "image/png" | "image/jpeg" | "image/webp" | "image/gif";

export function mediaTypeFor(path: string): ImageMediaType {
  const ext = path.split(".").pop()?.toLowerCase();
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  if (ext === "gif") return "image/gif";
  return "image/png";
}
