import Anthropic from "@anthropic-ai/sdk";

export const anthropic = new Anthropic();

// Per-call model split — the two calls have different requirements:
//
// Persona generation runs ONCE per run and is the quality seed (specific,
// grounded people vs. archetypes), so it stays on Sonnet 5 — near-Opus
// reasoning, at intro pricing $2/$10 per MTok through 2026-08-31.
//
// The walkthrough is ~90% of the calls and the dominant cost. A/B on real
// screenshots showed Haiku 4.5 reaches the same findings (same friction/drop
// verdicts, same specific constraints named) at ~3× lower cost, so the
// cost-dominant bucket runs on Haiku. Both use thinking-off + structured
// outputs for speed and valid JSON.
export const MODEL_PERSONA = "claude-sonnet-5";
export const MODEL_WALK = "claude-haiku-4-5";

// Effective throughput in bytes/second. India is nominally on 4G/5G, but real
// experienced speed varies enormously — weak/congested signal, and especially
// a phone throttled to ~64kbps after the daily data pack runs out. Load time is
// COMPUTED from real screenshot bytes and passed into the prompt as a fact,
// never generated by the model.
const THROUGHPUT: Record<string, number> = {
  "5G": 1_500_000,
  "4G": 400_000,
  "Weak 4G": 100_000,
  Throttled: 12_000, // ~64kbps post-data-cap: a 300KB screen ≈ 25s
};

export function loadSeconds(bytes: number, connection: string): number {
  const bps = THROUGHPUT[connection] ?? THROUGHPUT["Weak 4G"];
  return Math.round((bytes / bps) * 10) / 10;
}

export type ImageMediaType = "image/png" | "image/jpeg" | "image/webp" | "image/gif";

export function mediaTypeFor(path: string): ImageMediaType {
  const ext = path.split(".").pop()?.toLowerCase();
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  if (ext === "gif") return "image/gif";
  return "image/png";
}
