import Anthropic from "@anthropic-ai/sdk";

export const anthropic = new Anthropic();

// Per-call model split — the two calls have different requirements:
//
// Persona generation runs ONCE per run and is the quality seed (specific,
// grounded people vs. archetypes), so it stays on Sonnet 5 — near-Opus
// reasoning, at intro pricing $2/$10 per MTok through 2026-08-31.
//
// The walkthrough is ~90% of the calls and the dominant cost. A/B on real
// screenshots showed Haiku 4.5 reaches the same findings (same friction/drop
// verdicts, same specific constraints named) at ~3× lower cost, so the
// cost-dominant bucket runs on Haiku. Both use thinking-off + structured
// outputs for speed and valid JSON.
export const MODEL_PERSONA = "claude-sonnet-5";
export const MODEL_WALK = "claude-haiku-4-5";

// Connection throughput in bytes/second, from the spec. Load time is COMPUTED
// from real screenshot bytes and passed into the prompt as a fact — never
// generated by the model.
const THROUGHPUT: Record<string, number> = { "2G": 30000, "3G": 120000, "4G": 400000 };

export function loadSeconds(bytes: number, connection: string): number {
  const bps = THROUGHPUT[connection] ?? THROUGHPUT["3G"];
  return Math.round((bytes / bps) * 10) / 10;
}

export type ImageMediaType = "image/png" | "image/jpeg" | "image/webp" | "image/gif";

export function mediaTypeFor(path: string): ImageMediaType {
  const ext = path.split(".").pop()?.toLowerCase();
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  if (ext === "gif") return "image/gif";
  return "image/png";
}
