import type { Persona, RunReport } from "./types";

const RANK = { dropped: 0, struggled: 1, completed: 2 } as const;

function outcomeLabel(p: Persona): string {
  if (p.outcome === "dropped") return `Left at screen ${p.dropped_at_screen}`;
  if (p.outcome === "struggled") return "Finished, struggled";
  return "Completed";
}

export function reportSlug(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "report"
  );
}

// Serialises the whole analysis to Markdown for download / pasting into
// Notion, a ticket, or another tool.
export function reportToMarkdown(r: RunReport): string {
  const reached = r.personas.filter((p) => p.outcome !== "dropped").length;
  const out: string[] = [];

  out.push(`# ${r.title}`, "");
  if (r.description) out.push(r.description, "");
  out.push(`**${r.personas.length} users tested · ${reached} of ${r.personas.length} reached the end**`, "");
  out.push(`Flow: ${r.screens.map((s) => s.label || `Screen ${s.position}`).join(" → ")}`, "");
  out.push("---", "");

  const sorted = [...r.personas].sort(
    (a, b) => RANK[a.outcome] - RANK[b.outcome] || (a.dropped_at_screen ?? 99) - (b.dropped_at_screen ?? 99),
  );

  out.push("## By user", "");
  for (const p of sorted) {
    out.push(`### ${p.name}, ${p.age}, ${outcomeLabel(p)}`);
    out.push(`*${p.language} · ${p.connection} · ${p.device}*`, "");
    out.push(p.context, "");
    for (const s of p.steps) {
      const screen = r.screens.find((sc) => sc.id === s.screen_id);
      const load = s.metrics?.load_seconds != null ? ` · ${s.metrics.load_seconds}s load` : "";
      out.push(`**${s.position}. ${screen?.label || `Screen ${s.position}`}** (${s.status}${load})`);
      out.push(s.narrative);
      if (s.suggestion) out.push(`> **Fix:** ${s.suggestion}`);
      out.push("");
    }
    out.push("---", "");
  }

  out.push("## By screen", "");
  for (const sc of r.screens) {
    const rows = r.personas
      .map((p) => ({ p, step: p.steps.find((st) => st.screen_id === sc.id) }))
      .filter((x): x is { p: Persona; step: NonNullable<typeof x.step> } => x.step != null);
    out.push(`### ${sc.position}. ${sc.label || `Screen ${sc.position}`}`, "");
    for (const { p, step } of rows) {
      out.push(
        `- **${p.name.split(" ")[0]}** (${step.status}): ${step.narrative}${step.suggestion ? `  _Fix: ${step.suggestion}_` : ""}`,
      );
    }
    out.push("");
  }

  out.push(
    "",
    "_Generated by Setu · सेतु, a cheap first pass against non-urban Indian users. Not a replacement for real field testing; it clears the obvious breaks so real testing is spent on what only real people can tell you._",
  );
  return out.join("\n");
}
